coverage:
  precision: 2
  round: down
  range: 50...70

  status:
    project:
      default:
        target: 80
        threshold: 0.5%
    patch:
      default:
        target: 60

comment:
  layout: 'header, diff, changes, uncovered'
  behavior: default
