sudo: false
language: python

python: 3.5

env:
  matrix:
    - TOXENV=pep8
    - TOXENV=py27-rc

matrix:
  fast_finish: true

cache:
  pip: true

services:
  - redis

git:
  depth: 3

branches:
  only:
    - master

install:
  - pip install tox

script:
  - tox -vv

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
