language: python

python:
  - "2.7"

services:
  - redis

git:
  depth: 3

branches:
  only:
    - master

install:
  - pip install tox

script:
  - tox -e pep8
  - tox -e py

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
