sudo: false
language: python

python: 3.5

env:
  - TOXENV=pep8
  - TOXENV=py27-rc
  - TOXENV=py27-rediscluster
  - TOXENV=py35-rediscluster

cache:
  pip: true

services:
  - redis-server

branches:
  only:
    - master

install:
  - pip install tox

script:
  - .ci/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
